MESSAGE_GROUPS = {
    "A-737": {
        "317": {
            "description": "Từ nhận dạng",
        },
        "210": {
            "description": "Vĩ độ",
            "fields": [
                {
                    "name": "vi_do",
                    "start_pos": 2,
                    "end_pos": 23,
                    "min_val": 0,
                    "max_val": 180,
                },
            ],
        },
        "211": {
            "description": "Kinh độ",
            "fields": [
                {
                    "name": "kinh_do",
                    "start_pos": 2,
                    "end_pos": 23,
                    "min_val": 0,
                    "max_val": 180,
                },
            ],
        },
        "010": {
            "description": "Vĩ độ mở rộng / kinh độ mở rộng",
            "fields": [
                {
                    "name": "vi_do_mo_rong",
                    "start_pos": 2,
                    "end_pos": 12,
                    "min_val": 0,
                    "max_val": 0.000086,
                },
                {
                    "name": "kinh_do_mo_rong",
                    "start_pos": 12,
                    "end_pos": 22,
                    "min_val": 0,
                    "max_val": 0.000086,
                },
            ],
        },
        "223": {
            "description": "Độ cao của anten vệ tinh so với mực nước biển (m)",
            "fields": [
                {
                    "name": "do_cao_cua_anten_ve_tinh_so_voi_muc_nuoc_bien",
                    "start_pos": 2,
                    "end_pos": 23,
                    "min_val": 0,
                    "max_val": 131072,
                },
            ],
        },
        "266": {
            "description": "Vận tốc theo hướng bắc (km/h)",
            "fields": [
                {
                    "name": "van_toc_theo_huong_bac",
                    "start_pos": 2,
                    "end_pos": 23,
                    "min_val": 0,
                    "max_val": 6068.6336,
                },
            ],
        },
        "267": {
            "description": "Vận tốc theo phương đông (km/h)",
            "fields": [
                {
                    "name": "van_toc_theo_huong_dong",
                    "start_pos": 2,
                    "end_pos": 23,
                    "min_val": 0,
                    "max_val": 6068.6336,
                },
            ]
        },
        "264": {
            "description": "Vận tốc theo hướng thẳng (km/h)",
            "fields": [
                {
                    "name": "van_toc_theo_huong_thang",
                    "start_pos": 2,
                    "end_pos": 23,
                    "min_val": 0,
                    "max_val": 6068.6336,
                },
            ],
        },
        "324": {
            "description": "Thời gian ghi dữ liệu (giờ - phút - giây)",
            "fields": [
                {
                    "name": "gio",
                    "start_pos": 3,
                    "end_pos": 8,
                    "min_val": 0,
                    "max_val": 32,
                },
                {
                    "name": "phut",
                    "start_pos": 8,
                    "end_pos": 14,
                    "min_val": 0,
                    "max_val": 64,
                },
                {
                    "name": "giay",
                    "start_pos": 14,
                    "end_pos": 20,
                    "min_val": 0,
                    "max_val": 64,
                },
            ],
        },
        "127": {
            "description": "Sai lệch thời gian (us)",
            "fields": [
                {
                    "name": "sai_lech_thoi_gian",
                    "start_pos": 2,
                    "end_pos": 23,
                    "min_val": 0,
                    "max_val": 209715.2,
                },
            ],
        },
        "320": {
            "description": "Sai số vị trí ước tính (m)",
            "fields": [
                {
                    "name": "sai_lech_vi_tri_uoc_tinh",
                    "start_pos": 2,
                    "end_pos": 17,
                    "min_val": 0,
                    "max_val": 32768,
                },
            ],
        },
        "126": {
            "description": "Thời gian (năm - tháng - ngày)",
            "fields": [
                {
                    "name": "nam",
                    "start_pos": 3,
                    "end_pos": 10,
                    "min_val": 0,
                    "max_val": 128,
                },
                {
                    "name": "thang",
                    "start_pos": 10,
                    "end_pos": 14,
                    "min_val": 0,
                    "max_val": 16,
                },
                {
                    "name": "ngay",
                    "start_pos": 14,
                    "end_pos": 19,
                    "min_val": 0,
                    "max_val": 32,
                },
            ],
        },
        "031": {
            "description": "Loại vệ tinh (số hiệu vị trí - hệ số suy hao - số lượng vệ tinh)",
            "fields": [
                {
                    "name": "so_hieu_vi_tri",
                    "start_pos": 3,
                    "end_pos": 9,
                    "min_val": 0,
                    "max_val": 64,
                },
                {
                    "name": "he_so_suy_hao",
                    "start_pos": 9,
                    "end_pos": 19,
                    "min_val": 0,
                    "max_val": 102.4,
                },
                {
                    "name": "so_luong_ve_tinh",
                    "start_pos": 19,
                    "end_pos": 23,
                    "min_val": 0,
                    "max_val": 16,
                },
            ],
        },
        "030": {
            "description": "Số lượng vệ tinh - tỷ số tín trên tạp - số kênh thu",
            "fields": [
                {
                    "name": "so_luong_ve_tinh",
                    "start_pos": 3,
                    "end_pos": 7,
                    "min_val": 0,
                    "max_val": 16,
                },
                {
                    "name": "ty_so_tin_tren_tap",
                    "start_pos": 7,
                    "end_pos": 15,
                    "min_val": 0,
                    "max_val": 25.6,
                },
                {
                    "name": "so_kenh_thu",
                    "start_pos": 15,
                    "end_pos": 19,
                    "min_val": 0,
                    "max_val": 16,
                },
            ],
        },
        "377": {
            "description": "Góc phương vị - góc ngẩng",
            "fields": [
                {
                    "name": "goc_phuong_vi",
                    "start_pos": 2,
                    "end_pos": 11,
                    "min_val": 0,
                    "max_val": 360,
                },
                {
                    "name": "goc_ngang",
                    "start_pos": 11,
                    "end_pos": 18,
                    "min_val": 0,
                    "max_val": 90,
                },
            ],
        },
        "153": {
            "description": "Mã phiên bản phần mềm (năm - tháng - lĩnh vực - loại phần mềm - mã số PMO)",
        },
    },
    # "Kh-31A (3B, 4B)": {
    #     "157",
    #     "141",
    #     "154",
    #     "156",
    #     "152",
    #     "150",
    #     "151",
    #     "155",
    #     "201",
    #     "153",
    # },
    # "PNK (5A)": {
    #     "331",
    #     "330",
    #     "277",
    #     "273",
    # },
    # "PNK (12A)": {
    #     "340",
    # },
    # "PNK (20A)": {
    #     "212",
    #     "210",
    #     "211",
    #     "266",
    #     "267",
    #     "214",
    #     "376",
    # },
    # "PNK (21A)": {
    #     "000",
    #     "204",
    #     "272",
    #     "241",
    #     "242",
    #     "240",
    # },
    # "PNK (25A)": {
    #     "370",
    #     "322",
    #     "323",
    #     "371",
    #     "333",
    #     "326",
    #     "327",
    #     "321",
    #     "373",
    #     "346",
    #     "227",
    # },
    # "PNK (18A)": {
    #     "223",
    #     "221",
    #     "230",
    #     "224",
    #     "225",
    #     "233",
    #     "226",
    # },
    # "PNK (11B)": {
    #     "221",
    #     "230",
    #     "214",
    #     "376",
    #     "346",
    #     "332",
    # },
    # "PNK (41A)": {
    #     "221",
    #     "230",
    #     "214",
    #     "376",
    #     "346",
    #     "332",
    # },
    # "SUO (9A)": {
    #     "243",
    #     "244",
    #     "246",
    #     "247",
    #     "250",
    #     "251",
    #     "252",
    #     "241",
    #     "242",
    #     "245",
    # },
    # "SUO (LS1)": {
    #     "215",
    #     "216",
    #     "217",
    #     "220",
    #     "222",
    #     "231",
    #     "232",
    #     "223",
    #     "210",
    #     "211",
    #     "221",
    #     "230",
    #     "214",
    #     "224",
    #     "225",
    #     "233",
    #     "226",
    #     "242",
    #     "240",
    #     "227",
    #     "245",
    # },
    # "SUO (LS3)": {
    #     "320",
    #     "323",
    #     "324",
    #     "325",
    #     "326",
    #     "327",
    #     "330",
    #     "331",
    #     "332",
    #     "340",
    #     "341",
    #     "342",
    #     "343",
    #     "344",
    #     "345",
    #     "346",
    #     "347",
    #     "350",
    #     "351",
    #     "352",
    # },
}

# LABEL_DESCRIPTIONS = {
#     # A-737
#     "317": "Từ nhận dạng",
#     "210": "Vĩ độ",
#     "211": "Kinh độ",
#     "010": "Vĩ độ mở rộng / kinh độ mở rộng",
#     "223": "Độ cao của anten vệ tinh so với mực nước biển (m)",
#     "266": "Vận tốc theo hướng bắc (km/h)",
#     "267": "Vận tốc theo phương đông (km/h)",
#     "264": "Vận tốc theo hướng thẳng (km/h)",
#     "324": "Thời gian ghi dữ liệu (giờ - phút - giây)",
#     "127": "Sai lệch thời gian (us)",
#     "320": "Sai số vị trí ước tính (m)",
#     "126": "Thời gian (năm - tháng - ngày)",
#     "031": "Loại vệ tinh (số hiệu vị trí - hệ số suy hao - số lượng vệ tinh)",
#     "030": "Số lượng vệ tinh - tỷ số tín trên tạp - số kênh thu",
#     "377": "Góc phương vị - góc ngẩng",
#     "153": "Mã phiên bản phần mềm (năm - tháng - lĩnh vực - loại phần mềm - mã số PMO)",
    # Kh-31A
    # "157": "Từ mã kiểm tra",
    # "141": "Cự ly",
    # "154": "Tốc độ tiếp cận",
    # "156": "Cự ly kích hoạt",
    # "152": "Góc tà / góc tà theo đường chân trời",
    # "150": "Góc nghiêng",
    # "151": "Góc ngẩng",
    # "155": "Lệnh đơn",
    # "201": "Từ mã SUO",
    # A-737 / Kh-31A
    # "153": "Mã phiên bản phần mềm (năm - tháng - lĩnh vực - loại phần mềm - mã số PMO) (A-737) / góc phương vị (Kh-31A) / cự ly bổ nhào (Kh-31A)",
# }
